
language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t dockerjbc/docker-react .

script:
  - docker run -e CI=true dockerjbc/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react2"
  env: "dockerreact2-env"
  bucket_name: "elasticbeanstalk-eu-central-1-239304981802"
  bucket_path: "docker-react2"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY2
  secret_access_key: "$AWS_SECRET_KEY2"


